logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    com.kamsan.book: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  codec:
    max-in-memory-size: 50MB
  mail:
    host: localhost
    port: 1025
    username: kamsan
    password: kamsan
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

aws:
  region: eu-north-1
  s3:
    buckets:
      users: users-management-dev

application:
  cors:
    allowed-origins:
      - "http://localhost:4200"
    allowed-methods:
      - "*"
    allowed-headers:
      - "*"
    exposed-headers:
      - "*"
    allow-credentials: true
    max-age: 3600
  security:
    jwt:
#      secret-key: 83D6F8199C5221853739BBA188178
  mailing:
    frontend:
      activation-account-url: http://localhost:4200/activate-account